#!/usr/bin/env bash
# So-key Ai — offline-friendly Android build toolchain bootstrap.
#
# Downloads, into a cache directory OUTSIDE the git tree, everything needed to
# produce a signed APK without the Android SDK and without Gradle:
#
#   JDK ................. jdk4py (PyPI)          -> java / javac / keytool
#   aapt2 ............... aaptjs3 (npm)          -> resource compile + link
#   d8 / R8 ............. @drxiaozhi/minapk (npm)-> dex compilation
#   apksigner ........... @drxiaozhi/minapk (npm)-> APK signing (v1/v2/v3)
#   android.jar ......... @drxiaozhi/minapk (npm)-> platform stubs for d8
#   ecj ................. @drxiaozhi/minapk (npm)-> Java -> .class compiler
#
# The npm registry and PyPI are the only reachable indexes in the sandbox this
# project was bootstrapped in, hence the choice of packages. If you have a real
# Android SDK + Gradle, use ./gradlew (or the GitHub Actions workflow) instead.
set -euo pipefail

CACHE_DIR="${SOKEY_TOOLS_DIR:-$HOME/.cache/sokey-tools}"
NPM_CACHE="$CACHE_DIR/npm"
mkdir -p "$CACHE_DIR" "$NPM_CACHE"

# NB: kept on stderr so that `VAR="$(fetch_npm ...)"` only ever captures the path.
say() { printf '\033[1;36m[bootstrap]\033[0m %s\n' "$1" >&2; }
ok()  { printf '\033[1;32m  ok\033[0m %s\n' "$1" >&2; }
die() { printf '\033[1;31m  error\033[0m %s\n' "$1" >&2; exit 1; }

# ---------------------------------------------------------------- JDK (jdk4py)
JAVA_HOME_DIR="$CACHE_DIR/jdk4py-java"
if [ ! -x "$JAVA_HOME_DIR/bin/java" ]; then
  say "installing JDK (jdk4py) ..."
  PIP_ARGS=(install --quiet --target "$CACHE_DIR/pyjdk")
  python3 -m pip "${PIP_ARGS[@]}" jdk4py 2>/dev/null || \
    python3 -m pip "${PIP_ARGS[@]}" --break-system-packages jdk4py || \
    python3 -m pip "${PIP_ARGS[@]}" --break-system-packages --user jdk4py
  JHOME="$(PYTHONPATH="$CACHE_DIR/pyjdk" python3 -c 'import jdk4py; print(jdk4py.JAVA_HOME)')"
  [ -n "$JHOME" ] || die "could not resolve JAVA_HOME from jdk4py"
  rm -rf "$JAVA_HOME_DIR"; cp -r "$JHOME" "$JAVA_HOME_DIR"
fi
export JAVA_HOME="$JAVA_HOME_DIR"
export PATH="$JAVA_HOME/bin:$PATH"
ok "java $("$JAVA_HOME/bin/java" -version 2>&1 | head -1)"

# -------------------------------------------------------------- npm toolchain
fetch_npm () { # name version tarball-name
  local name="$1" version="$2" tarball="$3"
  if [ ! -f "$NPM_CACHE/$tarball" ]; then
    say "downloading npm package $name@$version ..."
    ( cd "$NPM_CACHE" && npm pack "$name@$version" --silent >/dev/null )
  fi
  local dir="$CACHE_DIR/${name//\//_}"
  if [ ! -d "$dir" ]; then
    mkdir -p "$dir"
    tar xzf "$NPM_CACHE/$tarball" -C "$dir" --strip-components=1
  fi
  printf '%s' "$dir"
}

AAPT_DIR="$(fetch_npm aaptjs3 2.0.2 aaptjs3-2.0.2.tgz)"
AAPT2="$AAPT_DIR/bin/x64/linux/aapt2"
[ -f "$AAPT2" ] || die "aapt2 not found at $AAPT2"
chmod +x "$AAPT2"   # tar does not always preserve the executable bit
ok "aapt2 $("$AAPT2" version 2>&1 | head -1)"

MINAPK_DIR="$(fetch_npm @drxiaozhi/minapk 0.4.0 drxiaozhi-minapk-0.4.0.tgz)"
for f in android.jar d8.jar apksigner.jar ecj-3.45.0.jar debug.keystore; do
  [ -f "$MINAPK_DIR/tools/$f" ] || die "missing build tool: $f"
done
ok "d8.jar / apksigner.jar / android.jar / ecj.jar / debug.keystore"

# ------------------------------------------------------------------- zipalign
# Not strictly required (aapt2/aligned zip + apksigner v2 works fine), and the
# npm zipalign helpers are Windows-only, so we ship a pure-python aligner that
# only runs when the APK is not already 4-byte aligned.
mkdir -p "$CACHE_DIR/bin"
cp "$(dirname "$0")/zipalign.py" "$CACHE_DIR/bin/zipalign.py" 2>/dev/null || true

cat > "$CACHE_DIR/env.sh" <<EOF
# generated by scripts/bootstrap-tools.sh — source me
export JAVA_HOME="$JAVA_HOME_DIR"
export PATH="$JAVA_HOME_DIR/bin:\$PATH"
export SOKEY_AAPT2="$AAPT2"
export SOKEY_ANDROID_JAR="$MINAPK_DIR/tools/android.jar"
export SOKEY_D8_JAR="$MINAPK_DIR/tools/d8.jar"
export SOKEY_APKSIGNER_JAR="$MINAPK_DIR/tools/apksigner.jar"
export SOKEY_ECJ_JAR="$MINAPK_DIR/tools/ecj-3.45.0.jar"
export SOKEY_DEBUG_KEYSTORE="$MINAPK_DIR/tools/debug.keystore"
EOF
say "toolchain ready — source $CACHE_DIR/env.sh"
